### ISSUE TITLE
Нет музыки

### ISSUE THREAD

**Issue by ShinyZero0** [PurpleHorrorRus/Meridius#35]
Скачал флатпак на федору. В аккаунт ВК вошел, но нигде нет музыки: главная страница пустая, а когда захожу в свою музыку пишет, что аудиозаписи закрыты. Отображается список друзей и групп, но там то же самое с музыкой. В журнале написано Access Denied

**Comment by PurpleHorrorRus** [comment]
Откройте инструменты разработчика и отправьте все красные ошибки. Ещё дайте ссылку на свою страницу и откройте аудиозаписи

**Comment by ShinyZero0** [comment]
```
Error: Cookies are corrupted
    at HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:87:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:98:24)
    at async HTTPClient.requestEndpoint (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:124:37)
    at async GeneralRequests.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/static.js:185:16)
    at async GeneralRequests.getSection (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/static.js:333:16)
    at async GeneralRequests.getRawGeneralPage (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/requests/general.js:23:29)
    at async GeneralRequests.load (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/requests/general.js:14:22)
_0x3ade12 @ 657b75e.js:1
```
```
Uncaught (in promise) Error: Cookies are corrupted
    at HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:87:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:98:24)
    at async HTTPClient.requestEndpoint (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:124:37)
    at async PlaylistsRequest.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/static.js:185:16)
    at async PlaylistsRequest.get (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/requests/playlists.js:23:21)
```
```
Error: Cookies are corrupted
    at HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:87:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPClient.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:98:24)
    at async HTTPClient.requestEndpoint (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/http.js:124:37)
    at async ExploreRequests.request (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/static.js:185:16)
    at async ExploreRequests.getSection (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/static.js:333:16)
    at async ExploreRequests.getRawExplorePage (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/requests/explore.js:107:29)
    at async ExploreRequests.load (/app/main/resources/app.asar/node_modules/easyvk-audio/lib/requests/explore.js:88:25)
```
```

TypeError: Cannot read properties of undefined (reading '$refs')
    at _0x2b11b6.removeTabs (a5a749f.js:1:12167)
    at _0x2b11b6.accessDenied (a5a749f.js:1:11110)
    at _0x2b11b6.accessDenied (67f747a.js:1:17575)
    at 67f747a.js:1:8638
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
Access Denied
(anonymous) @ 369e598.js:1
```

**Comment by ShinyZero0** [comment]
https://vk.com/kde_enjoyer
Ауидозаписи открыл, но ничего не изменилось

**Comment by ShinyZero0** [comment]
А где должна быть папка meridiusreborn? Никак найти не могу

**Comment by PurpleHorrorRus** [comment]
![image](https://user-images.githubusercontent.com/15189568/178425628-24974d2f-2482-4756-b92e-84ccf432e019.png)
Только что установил свежий образ Fedora на виртуальную машину и приложение запустилось всё так же без проблем. К тому же, жалоб от других пользователей на работоспособность приложения на их дистрибутивах (в том числе и Fedora) не поступало, потому по прежнему не могу подтвердить проблему со стороны приложения или библиотеки.

**Comment by ShinyZero0** [comment]
Понятно. Жаль что не заработало, но спасибо, что уделили время

**Comment by PurpleHorrorRus** [comment]
![image](https://user-images.githubusercontent.com/15189568/180279412-3d044f6a-f687-4c86-8c63-f3204b417f0b.png)

Столкнулся с той же проблемой, но в данный момент я флудил на севрера ВК запросами. Могу подтвердить только то, что симптомы сходятся, однако отпускает через 5 минут и далее авторизовывает спокойно. Не знаю, поможет ли вам эта информация, но на всякий случай это стоило упомянуть.
